### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify-http-proxy#43]
```sh
$ mkdir proxy-test && cd proxy-test
$ echo "{}" > package.json
$ npm i --save fastify fastify-http-proxy
# add https://github.com/fastify/fastify-http-proxy/blob/6a213c6c9e95d3f37559bdb9e18d360ccf0dd20b/example.js as `index.js`
$ node index.js
```

Result:

```
origin started http://localhost:61146
(node:30350) UnhandledPromiseRejectionWarning: Error: plugin must be a function
    at Boot.use (/private/tmp/02/proxy-test/node_modules/avvio/boot.js:187:11)
    at Object.server.(anonymous function) [as register] (/private/tmp/02/proxy-test/node_modules/avvio/boot.js:31:14)
    at startProxy (/private/tmp/02/proxy-test/index.js:30:10)
    at run (/private/tmp/02/proxy-test/index.js:45:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:30350) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:30350) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jsumners** [comment]
Forgot to change the `const proxy = require('.')` line. Ignore this issue.
